apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: gtc-demo-prefill-scaler
  namespace: dynamo-workload
spec:
  scaleTargetRef:
    apiVersion: nvidia.com/v1alpha1
    kind: DynamoGraphDeploymentScalingAdapter
    name: gtc-demo-trtllmprefillworker
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        query: |
          histogram_quantile(0.95, sum(rate(dynamo_frontend_time_to_first_token_seconds_bucket{dynamo_namespace="dynamo-workload-gtc-demo"}[5m])) by (le))
        threshold: "0.5"
        activationThreshold: "0.1"
