apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gtc-demo-letsencrypt-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gtc-2026-demo@digitalocean.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-access-token
              key: token
