apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loadgen-https
  namespace: dynamo-workload
spec:
  parentRefs:
    - name: gtc-demo-gateway
      namespace: cluster-services
      sectionName: https
  hostnames:
    - HOSTNAME_PLACEHOLDER
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: loadgen
          port: 3000
